#!/usr/bin/env python3
"""将运行时第三方依赖下载并解压到 ``src/_vendor/``，实现免 pip install 运行。

用法（在项目根目录）::

    python scripts/vendor_deps.py
    python scripts/vendor_deps.py --dry-run
    python scripts/vendor_deps.py --list

原理：
    1. ``pip install --target src/_vendor`` 拉取包及传递依赖
    2. 清理 ``.dist-info`` / ``bin`` / ``__pycache__``
    3. 写入 ``src/_vendor/VENDOR.lock`` 记录锁定版本

加载：``src/__init__.py`` 在 import 前将 ``src/_vendor`` 插入 ``sys.path``。
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VENDOR_DIR = REPO_ROOT / "src" / "_vendor"

# 与 pyproject.toml 注释及 src/ 实际 import 对齐
RUNTIME_PACKAGES = [
    "httpx>=0.25.0",
    "rich>=13.0.0",
    "pygments>=2.15.0",
    "urllib3>=2.0.0",
    "prompt_toolkit>=3.0.0",
]


def _run_pip_install(*, dry_run: bool) -> None:
    cmd = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--upgrade",
        "--target",
        str(VENDOR_DIR),
        *RUNTIME_PACKAGES,
    ]
    print("Running:", " ".join(cmd))
    if dry_run:
        return
    subprocess.run(cmd, check=True, cwd=REPO_ROOT)


def _clean_vendor_dir(vendor_dir: Path, *, keep_gitkeep: bool = True) -> None:
    vendor_dir.mkdir(parents=True, exist_ok=True)
    for item in vendor_dir.iterdir():
        if keep_gitkeep and item.name == ".gitkeep":
            continue
        if item.is_dir():
            shutil.rmtree(item)
        else:
            item.unlink()


def _prune_vendor_artifacts(vendor_dir: Path) -> None:
    for dist_info in vendor_dir.glob("*.dist-info"):
        shutil.rmtree(dist_info)
    bin_dir = vendor_dir / "bin"
    if bin_dir.is_dir():
        shutil.rmtree(bin_dir)
    for cache in list(vendor_dir.rglob("__pycache__")):
        shutil.rmtree(cache)
    for pyc in vendor_dir.rglob("*.pyc"):
        pyc.unlink(missing_ok=True)


def _write_lock_file(vendor_dir: Path) -> None:
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--path", str(vendor_dir)],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT,
    )
    lock_path = vendor_dir / "VENDOR.lock"
    header = (
        "# Auto-generated by scripts/vendor_deps.py — do not edit manually\n"
        f"# Python: {sys.version.split()[0]}\n"
    )
    lock_path.write_text(header + result.stdout, encoding="utf-8")
    print(f"Wrote {lock_path.relative_to(REPO_ROOT)}")


def _verify_imports(vendor_dir: Path) -> None:
    """Quick smoke test: vendor path + key imports."""
    sys.path.insert(0, str(vendor_dir))
    import httpx  # noqa: F401
    import rich  # noqa: F401
    import pygments  # noqa: F401
    import urllib3  # noqa: F401
    import prompt_toolkit  # noqa: F401
    print("Verify OK: httpx, rich, pygments, urllib3, prompt_toolkit")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Download runtime dependencies into src/_vendor/"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print pip command only, do not download",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List packages to vendor and exit",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Do not remove existing _vendor contents before install",
    )
    parser.add_argument(
        "--no-verify",
        action="store_true",
        help="Skip import verification after install",
    )
    args = parser.parse_args()

    if args.list:
        print("Packages to vendor:")
        for pkg in RUNTIME_PACKAGES:
            print(f"  - {pkg}")
        print(f"Target: {VENDOR_DIR}")
        return 0

    if not args.dry_run and not args.no_clean:
        print(f"Cleaning {VENDOR_DIR.relative_to(REPO_ROOT)} ...")
        _clean_vendor_dir(VENDOR_DIR)
        gitkeep = VENDOR_DIR / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.touch()

    _run_pip_install(dry_run=args.dry_run)

    if args.dry_run:
        return 0

    _write_lock_file(VENDOR_DIR)
    print("Pruning .dist-info / bin / __pycache__ ...")
    _prune_vendor_artifacts(VENDOR_DIR)

    if not args.no_verify:
        _verify_imports(VENDOR_DIR)

    print()
    print("Done. Run without pip install:")
    print(f"  python -m src.main --project-dir {REPO_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
